//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xenko.LauncherApp.Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Xenko.LauncherApp.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 It seems you do not have any version of Xenko currently installed. Would you like to install the latest version? 的本地化字符串。
        /// </summary>
        public static string AskInstallVersion {
            get {
                return ResourceManager.GetString("AskInstallVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Would you like to install the latest version of the Visual Studio integration? This is highly recommended for programmers! 的本地化字符串。
        /// </summary>
        public static string AskInstallVSIX {
            get {
                return ResourceManager.GetString("AskInstallVSIX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Help us improve Xenko! We are making an online survey that takes about 5 minutes to complete. Would you like to answer it? 的本地化字符串。
        /// </summary>
        public static string AskSurvey {
            get {
                return ResourceManager.GetString("AskSurvey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Close the launcher after starting Xenko 的本地化字符串。
        /// </summary>
        public static string AutoCloseLauncher {
            get {
                return ResourceManager.GetString("AutoCloseLauncher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Ask a question 的本地化字符串。
        /// </summary>
        public static string ButtonAnswers {
            get {
                return ResourceManager.GetString("ButtonAnswers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Chat with us 的本地化字符串。
        /// </summary>
        public static string ButtonDiscord {
            get {
                return ResourceManager.GetString("ButtonDiscord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Discuss about Xenko 的本地化字符串。
        /// </summary>
        public static string ButtonForums {
            get {
                return ResourceManager.GetString("ButtonForums", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Fork on GitHub 的本地化字符串。
        /// </summary>
        public static string ButtonGithub {
            get {
                return ResourceManager.GetString("ButtonGithub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Report an issue 的本地化字符串。
        /// </summary>
        public static string ButtonIssues {
            get {
                return ResourceManager.GetString("ButtonIssues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Check the roadmap 的本地化字符串。
        /// </summary>
        public static string ButtonRoadmap {
            get {
                return ResourceManager.GetString("ButtonRoadmap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Show us your work 的本地化字符串。
        /// </summary>
        public static string ButtonShowcase {
            get {
                return ResourceManager.GetString("ButtonShowcase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Answer the survey 的本地化字符串。
        /// </summary>
        public static string ButtonSurvey {
            get {
                return ResourceManager.GetString("ButtonSurvey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Are you sure you wish to uninstall version {0}? 的本地化字符串。
        /// </summary>
        public static string ConfirmUninstall {
            get {
                return ResourceManager.GetString("ConfirmUninstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Details: 的本地化字符串。
        /// </summary>
        public static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Downloading release notes… 的本地化字符串。
        /// </summary>
        public static string DownloadingReleaseNotes {
            get {
                return ResourceManager.GetString("DownloadingReleaseNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 An error occurred while trying to process a developer version: {0} 的本地化字符串。
        /// </summary>
        public static string ErrorDevRedirect {
            get {
                return ResourceManager.GetString("ErrorDevRedirect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unable to find the version {0}. This project cannot be open. 的本地化字符串。
        /// </summary>
        public static string ErrorDoNotFindVersion {
            get {
                return ResourceManager.GetString("ErrorDoNotFindVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 An error occurred while installing version {0}. 的本地化字符串。
        /// </summary>
        public static string ErrorInstallingVersion {
            get {
                return ResourceManager.GetString("ErrorInstallingVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 An error occurred while installing Visual Studio plugin. 的本地化字符串。
        /// </summary>
        public static string ErrorInstallingVSIX {
            get {
                return ResourceManager.GetString("ErrorInstallingVSIX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unable to connect to Xenko server. Switching to offline mode… 的本地化字符串。
        /// </summary>
        public static string ErrorOfflineMode {
            get {
                return ResourceManager.GetString("ErrorOfflineMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 An error occurred while trying to open a web browser 的本地化字符串。
        /// </summary>
        public static string ErrorOpeningBrowser {
            get {
                return ResourceManager.GetString("ErrorOpeningBrowser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 An error occurred while attempting to start the program: {0} 的本地化字符串。
        /// </summary>
        public static string ErrorStartingProcess {
            get {
                return ResourceManager.GetString("ErrorStartingProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 An error occurred while uninstalling version {0}. 的本地化字符串。
        /// </summary>
        public static string ErrorUninstallingVersion {
            get {
                return ResourceManager.GetString("ErrorUninstallingVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 An error occurred while uninstalling Visual Studio plugin. 的本地化字符串。
        /// </summary>
        public static string ErrorUninstallingVSIX {
            get {
                return ResourceManager.GetString("ErrorUninstallingVSIX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The version {0} is being updated. Please wait a moment. 的本地化字符串。
        /// </summary>
        public static string ErrorVersionBeingUpdated {
            get {
                return ResourceManager.GetString("ErrorVersionBeingUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The version {0} is not currently installed. Do you want to install it now? 的本地化字符串。
        /// </summary>
        public static string ErrorVersionNotInstalled {
            get {
                return ResourceManager.GetString("ErrorVersionNotInstalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The installation of this version is already in progress. Please wait a moment. 的本地化字符串。
        /// </summary>
        public static string InstallAlreadyInProgress {
            get {
                return ResourceManager.GetString("InstallAlreadyInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Install latest version 的本地化字符串。
        /// </summary>
        public static string InstallLatestVersion {
            get {
                return ResourceManager.GetString("InstallLatestVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 GLP 启动器 的本地化字符串。
        /// </summary>
        public static string LauncherTitle {
            get {
                return ResourceManager.GetString("LauncherTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Posted on {0:d MMM yyyy} 的本地化字符串。
        /// </summary>
        public static string NewsDate {
            get {
                return ResourceManager.GetString("NewsDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unable to fetch documentation 的本地化字符串。
        /// </summary>
        public static string NoDocumentation {
            get {
                return ResourceManager.GetString("NoDocumentation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unable to fetch news feed 的本地化字符串。
        /// </summary>
        public static string NoNews {
            get {
                return ResourceManager.GetString("NoNews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No project created yet! 的本地化字符串。
        /// </summary>
        public static string NoProjectCreated {
            get {
                return ResourceManager.GetString("NoProjectCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unable to download release notes 的本地化字符串。
        /// </summary>
        public static string NoReleaseNotes {
            get {
                return ResourceManager.GetString("NoReleaseNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No version currently installed 的本地化字符串。
        /// </summary>
        public static string NoVersionInstalled {
            get {
                return ResourceManager.GetString("NoVersionInstalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open with {0} 的本地化字符串。
        /// </summary>
        public static string OpenProjectWithVersion {
            get {
                return ResourceManager.GetString("OpenProjectWithVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Projects 的本地化字符串。
        /// </summary>
        public static string Projects {
            get {
                return ResourceManager.GetString("Projects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Remove From List 的本地化字符串。
        /// </summary>
        public static string RemoveFromList {
            get {
                return ResourceManager.GetString("RemoveFromList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Checking… 的本地化字符串。
        /// </summary>
        public static string ReportChecking {
            get {
                return ResourceManager.GetString("ReportChecking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Deleting {0}… 的本地化字符串。
        /// </summary>
        public static string ReportDeletingVersion {
            get {
                return ResourceManager.GetString("ReportDeletingVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Discovering… 的本地化字符串。
        /// </summary>
        public static string ReportDiscovering {
            get {
                return ResourceManager.GetString("ReportDiscovering", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Downloading {0}… ({1}%) 的本地化字符串。
        /// </summary>
        public static string ReportDownloadingVersion {
            get {
                return ResourceManager.GetString("ReportDownloadingVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Downloading Visual Studio plugin… ({0}%) 的本地化字符串。
        /// </summary>
        public static string ReportDownloadingVSIX {
            get {
                return ResourceManager.GetString("ReportDownloadingVSIX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Installing prerequisites… 的本地化字符串。
        /// </summary>
        public static string ReportInstallingPrerequisites {
            get {
                return ResourceManager.GetString("ReportInstallingPrerequisites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Installing {0}… 的本地化字符串。
        /// </summary>
        public static string ReportInstallingVersion {
            get {
                return ResourceManager.GetString("ReportInstallingVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Installing Visual Studio plugin… 的本地化字符串。
        /// </summary>
        public static string ReportInstallingVSIX {
            get {
                return ResourceManager.GetString("ReportInstallingVSIX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Installing plugin for {0}… 的本地化字符串。
        /// </summary>
        public static string ReportVSIXInstallForVersion {
            get {
                return ResourceManager.GetString("ReportVSIXInstallForVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 退出 的本地化字符串。
        /// </summary>
        public static string SelfUpdateExit {
            get {
                return ResourceManager.GetString("SelfUpdateExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 一个新的版本的启动程序正在下载… 的本地化字符串。
        /// </summary>
        public static string SelfUpdateMessage {
            get {
                return ResourceManager.GetString("SelfUpdateMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 更新程序… 的本地化字符串。
        /// </summary>
        public static string SelfUpdateTitle {
            get {
                return ResourceManager.GetString("SelfUpdateTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Show in Explorer 的本地化字符串。
        /// </summary>
        public static string ShowInExplorer {
            get {
                return ResourceManager.GetString("ShowInExplorer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Start {0} 的本地化字符串。
        /// </summary>
        public static string StartVersion {
            get {
                return ResourceManager.GetString("StartVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Switch/update version 的本地化字符串。
        /// </summary>
        public static string SwitchOrUpdateVersion {
            get {
                return ResourceManager.GetString("SwitchOrUpdateVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Getting started 的本地化字符串。
        /// </summary>
        public static string TabGettingStarted {
            get {
                return ResourceManager.GetString("TabGettingStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 News 的本地化字符串。
        /// </summary>
        public static string TabNews {
            get {
                return ResourceManager.GetString("TabNews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Click here to hide beta versions 的本地化字符串。
        /// </summary>
        public static string ToggleHideBetaVersions {
            get {
                return ResourceManager.GetString("ToggleHideBetaVersions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Click here to show beta versions 的本地化字符串。
        /// </summary>
        public static string ToggleShowBetaVersions {
            get {
                return ResourceManager.GetString("ToggleShowBetaVersions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Ready 的本地化字符串。
        /// </summary>
        public static string ToolTipDefault {
            get {
                return ResourceManager.GetString("ToolTipDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Download and install version {0} 的本地化字符串。
        /// </summary>
        public static string ToolTipDownload {
            get {
                return ResourceManager.GetString("ToolTipDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Install the latest available version of Xenko 的本地化字符串。
        /// </summary>
        public static string ToolTipInstallLatestVersion {
            get {
                return ResourceManager.GetString("ToolTipInstallLatestVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open this project with a more recent version of Xenko (the project will be upgraded) 的本地化字符串。
        /// </summary>
        public static string ToolTipOpenAndUpgradeProject {
            get {
                return ResourceManager.GetString("ToolTipOpenAndUpgradeProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open &apos;{0}&apos; 的本地化字符串。
        /// </summary>
        public static string ToolTipOpenLink {
            get {
                return ResourceManager.GetString("ToolTipOpenLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Set current version to {0} 的本地化字符串。
        /// </summary>
        public static string ToolTipSetActiveVersion {
            get {
                return ResourceManager.GetString("ToolTipSetActiveVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Start Xenko Game Studio {0} 的本地化字符串。
        /// </summary>
        public static string ToolTipStartButton {
            get {
                return ResourceManager.GetString("ToolTipStartButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Uninstall version {0} 的本地化字符串。
        /// </summary>
        public static string ToolTipUninstall {
            get {
                return ResourceManager.GetString("ToolTipUninstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Download and update to version {0} 的本地化字符串。
        /// </summary>
        public static string ToolTipUpdate {
            get {
                return ResourceManager.GetString("ToolTipUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} Visual Studio plugin 的本地化字符串。
        /// </summary>
        public static string ToolTipVisualStudioPlugin {
            get {
                return ResourceManager.GetString("ToolTipVisualStudioPlugin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unknown version 的本地化字符串。
        /// </summary>
        public static string UnknownVersion {
            get {
                return ResourceManager.GetString("UnknownVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Xenko {0} 的本地化字符串。
        /// </summary>
        public static string VersionButton {
            get {
                return ResourceManager.GetString("VersionButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 (not installed) 的本地化字符串。
        /// </summary>
        public static string VersionButtonUninstalled {
            get {
                return ResourceManager.GetString("VersionButtonUninstalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 (update available) 的本地化字符串。
        /// </summary>
        public static string VersionButtonUpdateAvailable {
            get {
                return ResourceManager.GetString("VersionButtonUpdateAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Visual Studio plugin 的本地化字符串。
        /// </summary>
        public static string VisualStudioPlugin {
            get {
                return ResourceManager.GetString("VisualStudioPlugin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 A problem has occurred during the installation of Visual Studio plugin. Check that you have at least one of the compatible version of Visual Studio installed (2012, 2013 or 2015). 的本地化字符串。
        /// </summary>
        public static string VSIXInstallFailed {
            get {
                return ResourceManager.GetString("VSIXInstallFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Visual Studio plugin has been successfully installed. Please restart running instances of Visual Studio. 的本地化字符串。
        /// </summary>
        public static string VSIXInstallSucessful {
            get {
                return ResourceManager.GetString("VSIXInstallSucessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Install 的本地化字符串。
        /// </summary>
        public static string VSIXVerbInstall {
            get {
                return ResourceManager.GetString("VSIXVerbInstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Reinstall 的本地化字符串。
        /// </summary>
        public static string VSIXVerbReinstall {
            get {
                return ResourceManager.GetString("VSIXVerbReinstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Update 的本地化字符串。
        /// </summary>
        public static string VSIXVerbUpdate {
            get {
                return ResourceManager.GetString("VSIXVerbUpdate", resourceCulture);
            }
        }
    }
}
